version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile.backend 
    container_name: laravel_backend
    working_dir: /var/www
    env_file:
      - .env 
    networks:
      - app-network
    restart: unless-stopped
  backend_proxy:
    image: nginx:stable-alpine
    container_name: nginx_backend_proxy
    ports:
      - "8000:81" 
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:ro
    networks:
      - app-network
    depends_on:
      - backend 
  frontend_proxy:
    image: nginx:stable-alpine
    container_name: frontend_proxy
    ports:
      - "3000:80" 
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge


